# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PetHelper' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PetHelper
	# Pods for Firebase_Example
	pod 'Firebase/Core'
	pod ‘Firebase/Database’
	pod ‘Firebase/Auth’
	pod ‘KeychainSwift’
	pod 'Firebase/Storage'
	pod ‘Firebase/Crash’
	
    
    # Pods for Facebook
    pod 'Bolts'
    pod 'FBSDKCoreKit'
    pod 'FBSDKLoginKit'

end
